In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
dataset = pd.read_csv('iris.csv')

In [6]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(x)

[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+00 1.70e+00 2.

In [9]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

## Exercise 4 

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [13]:
print(x_train)

[[2.30e+01 4.60e+00 3.60e+00 1.00e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [6.60e+01 6.70e+00 3.10e+00 4.40e+00 1.40e+00]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [4.30e+01 4.40e+00 3.20e+00 1.30e+00 2.00e-01]
 [1.47e+02 6.30e+00 2.50e+00 5.00e+00 1.90e+00]
 [5.20e+01 6.40e+00 3.20e+00 4.50e+00 1.50e+00]
 [2.80e+01 5.20e+00 3.50e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [3.30e+01 5.20e+00 4.10e+00 1.50e+00 1.00e-01]
 [1.43e+02 5.80e+00 2.70e+00 5.10e+00 1.90e+00]
 [8.60e+01 6.00e+00 3.40e+00 4.50e+00 1.60e+00]
 [8.70e+01 6.70e+00 3.10e+00 4.70e+00 1.50e+00]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [8.20e+01 5.50e+00 2.40e+00 3.70e+00 1.00e+00]
 [1.34e+02 6.30e+00 2.80e+00 5.10e+00 1.50e+00]
 [1.38e+02 6.40e+00 3.10e+00 5.50e+00 1.80e+00]
 [7.60e+01 6.60e+00 3.00e+00 4.40e+00 1.40e+00]
 [1.10e+02 7.20e+00 3.60e+00 6.10e+00 2.50e+00]
 [9.70e+01 5.70e+00 2.90e+00 4.20e+00 1.

In [14]:
print(x_test)

[[7.40e+01 6.10e+00 2.80e+00 4.70e+00 1.20e+00]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [1.19e+02 7.70e+00 2.60e+00 6.90e+00 2.30e+00]
 [7.90e+01 6.00e+00 2.90e+00 4.50e+00 1.50e+00]
 [7.70e+01 6.80e+00 2.80e+00 4.80e+00 1.40e+00]
 [3.20e+01 5.40e+00 3.40e+00 1.50e+00 4.00e-01]
 [6.50e+01 5.60e+00 2.90e+00 3.60e+00 1.30e+00]
 [1.42e+02 6.90e+00 3.10e+00 5.10e+00 2.30e+00]
 [6.90e+01 6.20e+00 2.20e+00 4.50e+00 1.50e+00]
 [8.30e+01 5.80e+00 2.70e+00 3.90e+00 1.20e+00]
 [1.11e+02 6.50e+00 3.20e+00 5.10e+00 2.00e+00]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [3.70e+01 5.50e+00 3.50e+00 1.30e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [5.70e+01 6.30e+00 3.30e+00 4.70e+00 1.60e+00]
 [1.05e+02 6.50e+00 3.00e+00 5.80e+00 2.20e+00]
 [7.00e+01 5.60e+00 2.50e+00 3.90e+00 1.10e+00]
 [5.60e+01 5.70e+00 2.80e+00 4.50e+00 1.30e+00]
 [1.33e+02 6.40e+00 2.80e+00 5.60e+00 2.20e+00]
 [3.00e+01 4.70e+00 3.20e+00 1.60e+00 2.

In [15]:
print(y_train)

['Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 '

In [16]:
print(y_test)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']


In [19]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
print(x_train)

[[-1.21030717 -1.47393679  1.22037928 -1.5639872  -1.30948358]
 [-1.37240188 -0.13307079  3.02001693 -1.27728011 -1.04292204]
 [-0.21458252  1.08589829  0.09560575  0.38562104  0.28988568]
 [-1.46502743 -1.23014297  0.77046987 -1.21993869 -1.30948358]
 [-0.74717943 -1.7177306   0.32056046 -1.39196294 -1.30948358]
 [ 1.66108484  0.59831066 -1.25412249  0.72966956  0.95628954]
 [-0.53877194  0.72020757  0.32056046  0.44296246  0.42316645]
 [-1.09452523 -0.74255534  0.99542457 -1.27728011 -1.30948358]
 [-1.62712214 -0.98634915  1.22037928 -1.33462153 -1.30948358]
 [-0.9787433  -0.74255534  2.34515281 -1.27728011 -1.44276436]
 [ 1.56845929 -0.01117388 -0.80421307  0.78701097  0.95628954]
 [ 0.24854522  0.23261993  0.77046987  0.44296246  0.55644722]
 [ 0.27170161  1.08589829  0.09560575  0.5576453   0.42316645]
 [-1.34924549 -0.49876152  1.8952434  -1.39196294 -1.04292204]
 [-1.48818382 -0.49876152  1.44533399 -1.27728011 -1.30948358]
 [ 0.15591967 -0.37686461 -1.47907719 -0.01576889 -0.24

In [21]:
print(x_test)

[[-0.0556222   0.14443512 -0.63451517  0.45110832 -0.07943674]
 [-1.31283631 -0.33701527  2.00929805 -1.2060243  -1.20827465]
 [ 0.97300752  2.07023667 -1.16327782  1.66633891  1.30025404]
 [ 0.05866999  0.02407252 -0.37013385  0.34063282  0.29684256]
 [ 0.01295312  0.98697329 -0.63451517  0.50634608  0.17141613]
 [-1.01567661 -0.69810306  0.95177276 -1.3164998  -1.08284822]
 [-0.26134814 -0.45737787 -0.37013385 -0.15650697  0.04598969]
 [ 1.49875161  1.10733589  0.15862879  0.67205934  1.30025404]
 [-0.16991439  0.26479771 -2.22080311  0.34063282  0.29684256]
 [ 0.15010374 -0.21665267 -0.8988965   0.00920629 -0.07943674]
 [ 0.79014002  0.6258855   0.42301012  0.67205934  0.92397473]
 [-1.44998694 -1.42027864 -0.10575253 -1.37173756 -1.45912752]
 [-0.90138442 -0.57774046  1.21615408 -1.42697531 -1.33370109]
 [-1.51856225 -1.29991605  0.15862879 -1.3164998  -1.45912752]
 [-1.28997787 -1.05919085  2.00929805 -1.3164998  -1.20827465]
 [-0.44421565  0.38516031  0.68739144  0.45110832  0.42